### ISSUE TITLE
Demo content

### ISSUE THREAD

**Issue by Sommerregen** [robbinfellow/haywire-grav#1]
Hi @robbinfellow ,

can you provide a demo content of the pages you used? You can just place them in the `_demo` folder of your theme.

**Comment by robbinfellow** [comment]
Hi @Sommerregen,

I've added the demo content to the repo, thanks for feedback 👍

**Comment by Sommerregen** [comment]
Thanks :+1:

**Comment by robbinfellow** [comment]
No problem, thanks for trying out the theme - all feedback is much appreciated! :)
