### ISSUE TITLE
Haywire / Laravel Mix / Webpack / BrowserSync not reloading on change

### ISSUE THREAD

**Issue by austinrivas** [robbinfellow/haywire-grav#10]
## Submit a bug report or feature request

- [ ] This is a feature request
- [x] This is a bug report
- [ ] This is a help-wanted
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/robbinfellow/haywire-grav/issues)

***

#### Subject of the issue

Love the theme and the attention to detail you have put into it. I am wondering if you have been able to get BrowserSync working in your Grav applications.

#### Your environment
* browser (including version) - Chrome / Safari / Edge
* OS - MacOSX 10.12.6
* Application running within a docker container using Nginx / PHP-fpm

#### Steps to reproduce

add browserSync to webpack.mix.js

```
var mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.setPublicPath('dist')
   .js('js/app.js', 'js/app.js')
   .sass('sass/app.sass', 'css/app.css')
   .options({
      processCssUrls: false
    });

mix.browserSync({
    proxy: 'localhost'
});
```

#### Expected behaviour

Editing a SASS or JS file should trigger a reload.

#### Actual behaviour

BrowserSync initializes on load but no reloads are triggered.

***

#### Question

I know it is out of scope for your theme, I am just wondering if this error is an artifact of my environment or a known issue for the theme.

Thanks again,
Austin

**Comment by robbinfellow** [comment]
Hi @austinrivas ,

Thanks for the kind words, I'm glad you like the theme. I've looked into browserSync. Looks like you have forgotten to assign which files should trigger a reload by browserSync.

I've tested in my local environment by adding a files parameter to browserSync and it's working as expected, I'm using Laravel Valet:

```
files: [
  'dist/css/{*,**/*}.css',
  'dist/js/{*,**/*}.js',
  'templates/{*,**/*}.html.twig'
]
```

This is the full mix setup I'm using in the working example:

```
mix.setPublicPath('dist')
   .js('js/app.js', 'js/app.js')
   .sass('sass/app.sass', 'css/app.css')
   .options({
      processCssUrls: false
    })
   .browserSync({
        proxy: 'haywire-grav.dev',
        port: 8000,
        files: [
            'dist/css/{*,**/*}.css',
            'dist/js/{*,**/*}.js',
            'templates/{*,**/*}.html.twig'
        ]
    });
```

Don't forget to add the following packages to `package.json` for browserSync to work:

```
"browser-sync": "^2.18.13",
"browser-sync-webpack-plugin": "^1.2.0",
```

I hope this solves your issue, 👍

**Comment by austinrivas** [comment]
yeah that did it, thanks @robbinfellow!
