### ISSUE TITLE
Responsive problem with Highlight

### ISSUE THREAD

**Issue by STnetwork** [robbinfellow/haywire-grav#11]
## Submit a bug report or feature request

- [ ] This is a feature request
- [x] This is a bug report
- [ ] This is a help-wanted
- [x] This request isn't a duplicate of an [existing issue](https://github.com/robbinfellow/haywire-grav/issues)

***

### Bug report
Hi, There is problem when I add an Highlight on a page, the responsive doesn't work well, check on this page for example : https://stnetwork.fr/linux/centos/softether-vpn-on-a-centos-7-vps-using-local-bridge-dnsmasq

This only happen when I add an Highlight as you will on the other pages like home, the responsive works well, thanks to solve this problem please. Thanks !

#### Your environment

CentOS 7 CENTMINMOD Nginx
Last Version of Chrome

**Comment by robbinfellow** [comment]
Hi,
Seems to be an issue with Bulma itself. I have provided two codepens with workarounds:

### Working example:

Working example with the `pre` element as a direct child to `.column`:
https://codepen.io/robbinfellow/pen/qpVwoo

### Non working example:

Non-working example with the `pre` element as a direct child to `.content` _(I have provided a possible css fix in this pen, try uncomment the css)_:
https://codepen.io/robbinfellow/pen/NXwmEG

I hope this solves your issue, I will research this further to see if this is in fact a bug within the Bulma framework.

**Comment by STnetwork** [comment]
Thanks for your fast solution, it will be good for the moment, if you have some news tell me please.

**Comment by robbinfellow** [comment]
@STnetwork I researched the issue and found that code blocks in Bulma looks to be used as a `figure` element with a class of `.highlight`. 

However the Bulma code blocks inside `.content` inherits style from the standard `figure` element (text-center/margins), which I have made a PR for, I've also raised the issue with in the Bulma repo:

**PR:**
https://github.com/jgthms/bulma/pull/1591

I have updated the codepen from earlier with a working solution:
https://codepen.io/robbinfellow/pen/qpVwoo

Happy coding! 🤓
