### ISSUE TITLE
element

### ISSUE THREAD

**Issue by diomed** [robbinfellow/haywire-grav#13]
## Submit a bug report or feature request

- [x ] This is a feature request

***
### Feature request
Hello, bulma is great, I wonder would you mind 
making version of haywire with Element http://element.eleme.io/#/en-US ?

**Comment by robbinfellow** [comment]
Hi,

I'm not familiar with Element, never used it actually - looks very promising though!

The purpose of Haywire is to be a starter-theme with nothing but "essentials" pre-installed. I think it's best to leave it that way for now.

Maybe it would be a better idea to create a stand-alone theme based on Haywire using Element and publish it to the GPM? You are ofcourse free to clone this project and modify it fully to your needs and make your own release/version of it.

I hope that is a good enough answer, thanks for using this theme! 👍

**Comment by diomed** [comment]
>Maybe it would be a better idea to create a stand-alone theme based on Haywire using Element ..

yeah. that was my idea. I hoped you could do it maybe. but if not never mind.

**Comment by robbinfellow** [comment]
@diomed Sorry if I misunderstood the situation, if I get some extra time available I promise I will look into creating a new grav theme based on Element using Laravel mix and Vue.js.

I will let you know 👍

**Comment by diomed** [comment]
ok. thanks a lot.
