### ISSUE TITLE
[BUG] Undefined index: assetPath upon upgrade

### ISSUE THREAD

**Issue by ganar** [robbinfellow/haywire-grav#15]
## Submit a bug report or feature request

- [X] This is a bug report

***

#### Subject of the issue
Describe your issue here.

"Undefined index: assetPath" after upgrading to the last version. switching back to `0.3.1` solves the issue

<img width="1275" alt="screen shot 2018-02-06 at 12 34 59 pm" src="https://user-images.githubusercontent.com/431185/35868246-b718f13c-0b3a-11e8-80fc-de7b4fd8d476.png">

#### Your environment
* Running on Docker with no isssues
* OSX High Sierra
* Chrome and Firefox

#### Steps to reproduce
Updated from `0.3.1` to the most recent version

#### Expected behaviour
the Template should not have problems with `assetPath`

**Comment by robbinfellow** [comment]
Hi,

It looks to me that the assetPath variable is missing in `haywire.yaml`, would you mind paste the code of that file for me to look?

[This](https://github.com/robbinfellow/haywire-grav/blob/4755f92dc9c21e7c5ccecda494cf1733907c1269/haywire.yaml#L1) line was added in `0.3.2`.

There have been some issues after I implemented asset cache busting in `0.3.2` so I might have to rollback the update. But please let me see the contents of `haywire.yaml` of your site/project first please :)

Thanks for using the theme, sorry for the inconvenience of the update.

**Comment by robbinfellow** [comment]
Fixed in `0.3.4`. 

Go ahead and update:

`$ bin/gpm update haywire`
