### ISSUE TITLE
Debug bar is not shown

### ISSUE THREAD

**Issue by chross** [robbinfellow/haywire-grav#16]
The debug bar needs jQuery to work.

So in the head.twig the following needs to be added:

```
{% if config.system.debugger.enabled %}
    {% do assets.addJs('jquery', 101) %}
{% endif %}
{{ assets.js() }}
```

See the following link:
https://muut.com/i/getgrav/general:debug-bar-does-not-show-up

**Comment by robbinfellow** [comment]
Great catch @chross! 👍 Totally missed this, sorry.

Fixed in 6428f09, will be included in `0.3.5`.
