### ISSUE TITLE
menu is not working on microsoft edge for android

### ISSUE THREAD

**Issue by samuelstein** [robbinfellow/haywire-grav#17]
I use your great theme with the latest grav cms. when i open the page on microsoft edge for android the burger menu will not open.

#### environment
* Microsoft edge 1.0.0
* Android 6.0.1

**Comment by robbinfellow** [comment]
Hi,
Thanks for using this theme, I cannot test in that kind of environment, only got Mac available for testing. 

Is there any way you can provide some additional information, e.g screenshot/console error message when hamburger is clicked?

**Comment by samuelstein** [comment]
the problem occurs on every mobile browser (safari, chrome, firefox). you can also test it if you use the device toolbar in google chrome dev tools

**Comment by robbinfellow** [comment]
Tested in chrome with the device toolbar, but I cannot seem to replicate the issue. Am I missing something here? (see gif)

**Chrome Version 64.0.3282.167 (Official Build) (64-bit)**

![Working navbar burger](https://thumbs.gfycat.com/LikablePlasticCopperhead-size_restricted.gif)

**Comment by samuelstein** [comment]
after installing your latest version and extending your theme it is working across the browsers. i don't know what the problem was but thanks a lot

**Comment by robbinfellow** [comment]
I'm glad you got it working again 👍
