### ISSUE TITLE
feature request: allow custom.css

### ISSUE THREAD

**Issue by samuelstein** [robbinfellow/haywire-grav#18]
would be great if the theme could allow custom modifications like animatter theme. 
should be easy :-). see: https://github.com/getgrav/grav-theme-antimatter/blob/develop/templates/partials/base.html.twig#L17

**Comment by robbinfellow** [comment]
Correct me if I missunderstand you now but it's already possible to add custom style:

First tell laravel mix to watch your assets:

```shell
$ cd user/themes/haywire
$ yarn watch
```

Add custom style for example in `resources/sass/common/_general.sass`:

```sass
body
  background: pink
```

Preferably create your own custom `.sass` files to fit your project, just make sure to `@import` new files in `app.sass`.

Laravel Mix will handle compiling for you, all style from `resources/sass/app.sass` will all be compiled and output in `dist/css/app.css` which is already included in `<head>`:
https://github.com/robbinfellow/haywire-grav/blob/af4b2022023bf17b7c1a2f80e33f5048000165f3/templates/partials/head.html.twig#L7

If you want to have minified css output simply run `yarn production` when you're finished working with your assets.

I hope I understood your question correctly 👀

**Comment by samuelstein** [comment]
ah. thanks for clarifying. i didn't know that i have to define it in app.sass. would be great if it is mentioned in documentation

**Comment by robbinfellow** [comment]
Thanks for your feedback, I will update the readme to make it more understandable on how to work with assets.

Sorry if it's a bit confusing atm!
