### ISSUE TITLE
These Fields

### ISSUE THREAD

**Issue by diomed** [robbinfellow/haywire-grav#20]
### Feature request

![screenshot_35](https://user-images.githubusercontent.com/72777/38083844-15f2be8a-334b-11e8-9333-43d6d8279bba.png)

Hello
I was wondering could you maybe add these option fields to your theme?
These are taken from [here](https://github.com/tranduyhung/grav-theme-clean-blog)

**Comment by robbinfellow** [comment]
Hi,

FontAwesome is not used in this theme and it's not a package I want to include. However adding custom fields for something like default **footer text** and **404 message** could be a nice addition to the theme.

Do you have any ideas of which fields to add? (other than footer/404 text)

It's pretty simple really if you want to modify this section on your own as well, you can add/remove any fields you want in the theme `blueprints.yaml` file ([link](https://github.com/robbinfellow/haywire-grav/blob/07d6960ca16f088cd54e0ac5792184fd4604d8b1/blueprints.yaml#L15)).

**Comment by diomed** [comment]
upload favicon field would be nice
also, it should be possible to change keywords in SEO easily

Lets talk about Font Awesome 
I understand you don't want to add unnecessary files; is this the reason?
What do you say about including it from grav-plugin-admin like this:

`{% do assets.addJs('plugin://admin/themes/grav/fonts') %}`

**Comment by FullZero5** [comment]
also, it should be possible to change keywords in SEO easily- Add a plugin [Auto SEO](https://github.com/gameamea/grav-plugin-autoseo) or any other for cms Grav

**Comment by robbinfellow** [comment]
After some consideration I have decided not to add additional fields in the theme blueprints for now.

**Reasons:**
- As you said; I do not want to bloat the theme with _"unnecessary"_ settings/packages, after all the purpose of this theme is to offer a solid foundation for developers building/extending themes on their own using the haywire-grav theme as a starting point.
- It's very easy to implement this type of feature on your own: [grav docs.](https://learn.getgrav.org/forms/blueprints/fields-available) (I'd be glad to help!)
- Relying on fonts included in the admin plugin is not an option, what if the admin plugin is not used at all? (sure you could probably check if it exists, but it feels wonky)
- As @FullZero5 mentioned, there are plugins for SEO purposes, also grav comes with plenty of options to add meta data such as `keywords` to your website, it's already implemented in grav core.

For now I will leave this theme as is regarding the blueprint settings. I hope you understand my reasoning.

Please let me know if you need help adding these fields in your version of this theme, I'd be glad to help! 👍

**Comment by diomed** [comment]
hi 
yes, if you could help me with setting up favicon field that would be great. 
other ones I've figured out, but uploading - basically path of it bugs me, and I get error,
can't figure it out.
