### ISSUE TITLE
How to connect vuex and other components?

### ISSUE THREAD

**Issue by FullZero5** [robbinfellow/haywire-grav#21]
#### Question
How to properly connect vuex and other components? Can you give an example?

yarn add vuex
`
window.Vue = require('vue');
window.Vuex = require('vuex');
Vue.config.devtools = true
Vue.use(Vuex)

`

**Comment by robbinfellow** [comment]
I have no experience using Vuex personally but it looks to me it should be pretty straight forward reading from the docs:

```shell
# @ path/to/grav/installation
$ cd user/themes/haywire
$ yarn add vuex --dev
$ yarn watch
```

Add the following to `resources/js/app.js`:

```js
// after you require Vue
import Vuex from 'vuex';
Vue.use(Vuex);
```

From here I would recommend looking at the examples from [Vuex docs](https://vuex.vuejs.org/en/getting-started.html).

Sorry if this wasn't much help, as I said – I have no personal experience from Vuex. 

Let me know how it goes, feel free to ask questions if you're still having troubles setting it all up and I'll try to help!

**Comment by FullZero5** [comment]
Thank you!
