### ISSUE TITLE
Adding page with list of post

### ISSUE THREAD

**Issue by luqmanrom** [robbinfellow/haywire-grav#22]
## Submit a bug report or feature request

- [ ] This is a feature request
- [ ] This is a bug report
- [X] This is a help-wanted
- [ ] This request isn't a duplicate of an [existing issue](https://github.com/robbinfellow/haywire-grav/issues)

#### Question
Having troubles with something theme-related? Please describe your problem as detailed as possible.

I added a post using page template item, and now I wanted to have a page with list of posts. From what I understand, it just adding a blog page, but it doesnt show up. Can you direct me to the right direction?

**Comment by robbinfellow** [comment]
Hello,

How does your folder setup look? Also, make sure you are using the correct templates of both the blog page and the posts.

#### Your folder structure should look something like this:

![Imgur](https://i.imgur.com/C9uIHTy.png)

Make sure to use the `blog` template in your blog page, `02.blog/blog.md` in this case:

``` markdown
---
title: Blog
visible: true
template: blog
---

My awesome blog!
```

Use the `item` template in the blog post itself, `01.fruitcake-chocolate-cake/blog.md` in this case:

``` markdown
---
title: 'Fruitcake chocolate cake'
featured_image: demo_01.jpg
intro: 'Some intro text'
published: true
publish_date: '2018-02-15 13:37'
taxonomy:
    tag:
        - some tag
visible: true
template: item
---

My awesome blog post!
```

You can iterate over your blog posts in any twig template doing something like this:
```twig
{% for post in page.find('/blog').children.order('publish_date', 'desc').slice(0, 3) %}
    {% include 'partials/post.html.twig' %}
{% endfor %}
```

Have a look at `user/themes/haywire/_demo/pages/` in this theme, hopefully that'll point you in the right direction.


Let me know if you're still having troubles!

**Comment by robbinfellow** [comment]
I will close this due to inactivity, if you feel your question wasn't answered, please feel free to re-open.
