### ISSUE TITLE
How to utilize vue?

### ISSUE THREAD

**Issue by diomed** [robbinfellow/haywire-grav#23]
- [x] This is a help-wanted
***

#### Question

Hi

I'd like to know more on how to utilize vue in this theme.
Like, could we automatically write data into .js files with vue in grav?
If you could explain what could be achieved, for example, I'd be grateful.

I know this is very general question but you don't have to answer extensively.

**Comment by robbinfellow** [comment]
👋  Hey,

Vue has no limitations to this theme, you can do anything vue-related really. There's a `Navbar.vue` component in the theme upon installation, use it as a [reference.](https://github.com/robbinfellow/haywire-grav/blob/develop/resources/js/components/Navbar.vue)

I'm not quite sure what you mean by writing data automatically, do you want to work with data via ajax? I'd recommend using something like `axios` for that.

---

Simple example of creating a custom vue component using this theme:

#### 1. Create a component

Create a new component in `resources/js/components/`, for example `resources/js/components/Example.vue`.

#### 2. Register the component globally

Open `resources/js/app.js` and register the component globally:

`Vue.component('example', require('./components/Example.vue'));`

#### 3. Call the component

Use the component anywhere you want inside `div#app`, works in any twig template/partial:

`<example></example>`

Hopefully this will nudge you in the right direction 👍

**Comment by FullZero5** [comment]
Оn the idea you need to install some kind of plugin for CMS Grav:

- [grav-plugin-api](https://github.com/Regaez/grav-plugin-api)

- [grav-plugin-api](https://github.com/flaviocopes/grav-plugin-api)

and then by means of the you work with the REST API [sampls](https://alligator.io/vuejs/rest-api-axios/)
