### ISSUE TITLE
up bulma

### ISSUE THREAD

**Issue by diomed** [robbinfellow/haywire-grav#24]
- [x] This is a feature update request

### Feature request

bulma is now in v. 0.7.1. 
so you'd probably wanna update it.

**Comment by robbinfellow** [comment]
Good call! Sorry for the delay, I'll update within a few days! 👍 

On a side note, I'm actually considering replacing Bulma with TailwindCSS, thoughts?

**Comment by diomed** [comment]
unsure why you'd change. isn't bulma ok?
[spectre](https://github.com/picturepan2/spectre) might be even better than bulma.

btw. maybe u could have multiple versions / repositories of haywire?
like haywire-bulma | haywire tailwind

I mean to ask you would you maybe do a version with [uikit](http://www.getuikit.com)

**Comment by robbinfellow** [comment]
Bulma is nice, I just think TailwindCSS suits me better.

Multiple repos for different versions of the theme isn't an option, harder to maintain. Although maybe I could provide multiple stubs/installations of this theme with different setups. I'll give it some thought! 👍

**Comment by mwarf** [comment]
Im really enjoying the Bulma version, I'd love if you kept that version going - any progress on a sticky footer?
