### ISSUE TITLE
Support: adding sourceMaps when not built for production

### ISSUE THREAD

**Issue by guategeek** [robbinfellow/haywire-grav#28]
First off thanks for creating a great start theme that lets more design focused guys like me use features I would have trouble setting up on my own.

I was wondering how I can add source maps to the theme when its running in watch mode, but have them disabled when I build for production. There is a lot going on with webpack and yarn I don't understand, which is great using what you already have. I just have trouble knowing how to extend it. I have used things like grunt or gulp but web-pack seems to go at it a bit differently.

**Comment by robbinfellow** [comment]
👋 Hey @guategeek!

This is possible by adding `mix.sourceMaps()` to `webpack.mix.js`.

By looking at the [original source code](https://github.com/JeffreyWay/laravel-mix/blob/add84aac0eaa91ebdb896706e9b21f4db28d9b4a/src/Api.js#L12) it seems `mix.sourceMaps()` accepts a parameter for if in production or not, would look something like this:

``` js
mix.js('resources/js/app.js', 'js/app.js')
   .sass('resources/sass/app.sass', 'css/app.css')
   .sourceMaps(false);
```

`mix.sourceMaps()` also accepts a second parameter type where you can specify the sourcemap type as stated [here.](https://github.com/JeffreyWay/laravel-mix/issues/1651#issuecomment-391693355)

Couldn't find much more information about this in the laravel mix docs, but it's mentioned in Laravel docs with a basic example:

https://laravel.com/docs/5.6/mix#css-source-maps

---

On a sidenote, it's possible to check for production for other api references as well by using `mix.inProduction()`, for example:

``` js
mix.js('resources/assets/js/app.js', 'public/js');

if (mix.inProduction()) {
    mix.version();
}
```

Let me know if you're still having troubles setting up sourcemaps and I'll help!

**Comment by guategeek** [comment]
Thanks so much for the help. Still took a lot of playing around to get things to work. 

With help from this [post](https://github.com/JeffreyWay/laravel-mix/issues/1548) and your comments, I was able to get source maps working as .map files in dev and watch, and not referenced when in production. Here is my webpack.mix.js setup if it can help anyone else

```js
mix.setPublicPath('dist')
  .webpackConfig({devtool:'source-map'})
  .sourceMaps(false)
  .js('resources/js/app.js', 'js/app.js')
  .sass('resources/sass/app.sass', 'css/app.css')
  .options({
    processCssUrls: false
  })
  .version();
```

**Comment by robbinfellow** [comment]
Great, I'm glad it's solved! Happy coding and thanks for using this theme! 🙌 

Closing this issue as it's resolved.
