### ISSUE TITLE
moving css to a higher level

### ISSUE THREAD

**Issue by pixelfabs** [robbinfellow/haywire-grav#31]
Hello :-)

Thank you for this theme! A true lifesaver :-D

I have trouble moving the CSS out of the dist/css directory and moving it to top level. I have looked through the Grav Theme docs, but I just cannot figure out what I have to do. Can you point me in the right direction?

Thank you.

**Comment by robbinjohansson** [comment]
👋 Hey,

Thanks for using my theme, glad you enjoy it!

To move assets to the root of the theme, there are two things you need to change:

1. Update webpack.mix.js PublicPath (`/user/themes/haywire/webpack.mix.js`):

```diff
- mix.setPublicPath('dist')
+ mix.setPublicPath('/')
```

2. Update path to the assets helper method (`/user/themes/haywire/haywire.php`):

```diff
public function onTwigSiteVariables()
    {
        // Asset cache busting handler
-       $manifest = __DIR__ . '/dist/mix-manifest.json';
+       $manifest = __DIR__ . '/mix-manifest.json';


        if (file_exists($manifest)) {
            $assets = json_decode(file_get_contents($manifest), true);
-           $this->grav['assets']->addJs('theme://dist/' . $assets['/js/app.js'],10);
-           $this->grav['assets']->addCss('theme://dist/' . $assets['/css/app.css'],10);
+           $this->grav['assets']->addJs('theme:/' . $assets['/js/app.js'],10);
+           $this->grav['assets']->addCss('theme:/' . $assets['/css/app.css'],10);
        }
# ...
    }
```

Don't forget to recompile your assets: 
```shell
# @ /user/themes/haywire
$ rm -rf dist/ && yarn production
```

Hopefully this will nudge you in the right direction no matter what directory structure you want for your compiled assets, let me know if you still have troubles setting it up.

**Comment by pixelfabs** [comment]
Thank you so much! I did a clean install of GravCMS + Admin to test. Everything works as you described. All commands and paths are correct and I can see the newly compiled files in the theme dir instead of dist dir. 

The **odd thing is that GravCMS removes the link to the overall CSS** after compiling. A normal clean install has this line in `<head></head>`:


`<link href="/dev/user/themes/haywire/dist/css/app.css?id=e2a5819dbcdf59c12975" type="text/css" rel="stylesheet" />`


But after doing all the commands, GravCMS no longer links to the newly generated CSS. It's just gone.

I went on and executed each direction you gave 1 by 1 on it's own, to see what causes this issue. I nailed it down to this change:

> 1. Update webpack.mix.js PublicPath (`/user/themes/haywire/webpack.mix.js`):
> 
> ```diff
> - mix.setPublicPath('dist')
> + mix.setPublicPath('/')
> ```

Any idea how to solve this?

PS. the need to move the CSS to a higher dir has to do with significantly faster loading speed. According to my tests, it's around 731ms faster.

**Comment by robbinjohansson** [comment]
Sorry but I cannot replicate your issue, following the steps I provided gives me the following output for the stylesheet, which is working as expected:

`<link href="/user/themes/haywire/css/app.css?id=b1627cfcc3472b470390" type="text/css" rel="stylesheet" />`

Tested this in a fresh install, are you sure you followed the exact steps I provided?

I'm using Laravel Valet.

**Please note only one `/` in the asset path change `theme://dist/` > `theme:/`:**

```diff
-           $this->grav['assets']->addJs('theme://dist/' . $assets['/js/app.js'],10);
-           $this->grav['assets']->addCss('theme://dist/' . $assets['/css/app.css'],10);
+           $this->grav['assets']->addJs('theme:/' . $assets['/js/app.js'],10);
+           $this->grav['assets']->addCss('theme:/' . $assets['/css/app.css'],10);
```

**Comment by pixelfabs** [comment]
Solved :-D Thank again for your help. I had some issues with npm/yarn etc.. on a windows machine. Your instructions are all correct. I must have missed something or a typo. In any case, I managed to move CSS out of the dist and place it where ever I want to.

**Comment by robbinjohansson** [comment]
Great to hear, closing as resolved 👍
