### ISSUE TITLE
Demo is Down

### ISSUE THREAD

**Issue by JREAM** [robbinfellow/haywire-grav#4]
https://haywire.me/haywire-grav-demo/

![themebug](https://cloud.githubusercontent.com/assets/145959/24734166/eeed059a-1a49-11e7-912f-4ee73941a345.png)

**Comment by robbinfellow** [comment]
Sorry about this, I've had some server issues lately - I'll set up a new demo shortly.

**Comment by robbinfellow** [comment]
@JREAM I've updated the demo site with a [new release](https://github.com/robbinfellow/haywire-grav/releases/tag/0.2.2)

[http://grav.haywire.me/](http://grav.haywire.me/)
