### ISSUE TITLE
Buefy - Vue.js based on Bulma

### ISSUE THREAD

**Issue by STnetwork** [robbinfellow/haywire-grav#7]
Hi,

I would like to start on your theme with : https://buefy.github.io/#/

Do you think it's possible ? and how I can start ?

**Comment by robbinfellow** [comment]
Hi @STnetwork,

It's possible, just follow the getting-started steps over at https://buefy.github.io/#/documentation/start after installing the Haywire theme.

Make sure you are using Vue 2.3.0+ as defined in the buefy documentation.

**Comment by STnetwork** [comment]
Vue 2.3.0+, isn't already installed on your theme ?

**Comment by robbinfellow** [comment]
It is, Vue should be the latest version(currently **2.4.2**) by running yarn from your theme root directory.

Otherwise you can always specify a version in the theme's `package.json` file manually 👍

**Comment by STnetwork** [comment]
Sorry for the delay I was able to make a website with your starter based on [Buefy](https://buefy.github.io/#/) Thanks !

here my website [STnetwork](https://stnetwork.fr/) .
Do you think It will be possible to find a way by the webpack or something else for generate a static website ? maybe by this way [Nuxt.JS](https://github.com/nuxt/nuxt.js), it's like next.js but for vuejs, and with it you can generate a static website.

**Comment by diomed** [comment]
@STnetwork hello. 

could you maybe open-source your grav buefy theme?

**Comment by STnetwork** [comment]
@diomed  here my theme I hope it will help you : https://github.com/STnetwork/git-sync-grav

**Comment by diomed** [comment]
thank you very much @STnetwork 👍

**Comment by STnetwork** [comment]
@diomed 
Hey, if you are interested, I updated the theme with the last version of haywire-grav 0.3.1, it's more simple with the native bulma theme : https://github.com/STnetwork/git-sync-grav
