### ISSUE TITLE
Manual installation in README

### ISSUE THREAD

**Issue by FistMeNaruto** [robbinfellow/haywire-grav#8]
## Submit a bug report or feature request

- [ ] This is a feature request
- [x] This is a bug report
- [ ] This is a help-wanted
- [x] This request isn't a duplicate of an [existing issue](https://github.com/robbinfellow/kaliber/issues)

***

### Bug report

Tiny error - it should be noted that if manual installation is chosen, users should navigate to `user/themes`, not `grav-installation` root.

https://github.com/robbinfellow/haywire-grav/blob/develop/README.md#manual-installation

**Comment by robbinfellow** [comment]
Thanks for noticing, @FistMeNaruto 👍
