### ISSUE TITLE
some small changes

### ISSUE THREAD

**Issue by diomed** [robbinfellow/haywire-grav#9]
## Submit a bug report or feature request

- [x] This is a feature request
- [x] This request isn't a duplicate of an [existing issue](https://github.com/robbinfellow/haywire-grav/issues)

***

### Feature request
Hello, 
I know this is visual request, but still, I hope you'll appreciate some of these suggestions.
I know that you're minifying everything, so I'll just write code here:
1. please add selection color:
```
::selection {
    background-color: #e8eaf6;
}

::-moz-selection {
  background-color: #e8eaf6;
}
```

2. if you would, please add nice modern scrollbar for webkit based browsers:
```
-webkit-scrollbar {
    width: 0;
}

::-webkit-scrollbar {
    width: 7px;
    height: 7px;
}
::-webkit-scrollbar-thumb {
    background-color: #ecf0f1;
    border-radius: 2px;
}
 
::-webkit-scrollbar-track {
    background-color: whitesmoke;
}
```
alternatively , you could look into implementing this:
https://github.serafin.io/vuebar/

3. Back to top [which is usual stuff in any theme]

#### Question
Since theme already uses vue with bulma, wouldn't it be good to make it use [buefy](https://buefy.github.io)?

Would you be willing to add a container around content, that distincts it from background?

Well, that's all. 
I gotta tell you how great it is that you switched over to bulma, 
and that you made that dropdown menu properly. That thing sure bugged me. 
Thank You for great theme! 👍 👍 👍 👍 👍

**Comment by robbinfellow** [comment]
Hi @diomed 👋 

Thank you for your suggestions, however considering its a boilerplate for fresh grav installations I’d like to keep the theme as stripped as possible from css/npm packages leaving it up to the developer to choose which packages to include. 

The goal of this theme is to offer a good and simple starting point with as little preset configurations as possible for new grav themes/projects. I feel it would be kinda counter-productive if people have to remove packages/code from the boilerplate theme upon installation.

I appreciate your suggestions and they are very welcome, also I’m glad you enjoy the theme. Feel free to fork the theme modifying it to fit your needs.

Thanks again for the feedback 🙏

**Comment by diomed** [comment]
would you mind adding some info in readme on what things exactly should one change when changing theme name to make their own version.

**Comment by robbinfellow** [comment]
There is no need to change the name of the theme when creating your own version, but if you want to change the name there's good documentation about it in the docs:

https://learn.getgrav.org/themes/customization
